### ISSUE TITLE
Dependency Injection / Service Locator

### ISSUE THREAD

**Issue by tomklecha** [Canato/Purity-Test#42]
I wanted to implement Hilt into our project, but unfortunately we cannot use it while using multi module app
https://developer.android.com/training/dependency-injection/hilt-multi-module

So we need to choose between Dagger 2 or Koin. I just wanted to know which of these two you want
For my perspective - I know the diffrence between both in theory and with the way we implemented
our project would make sense to use Koin - Service Locator.

**Comment by Canato** [comment]
If your multi-module project is composed of regular Gradle modules, then you can use Hilt as described in [Dependency injection with Hilt](https://developer.android.com/training/dependency-injection/hilt-android). However, this is not the case with apps that include [feature modules](https://developer.android.com/guide/app-bundle/dynamic-delivery#customize_delivery).

[About Feature Modules:](https://stackoverflow.com/questions/44140208/android-library-module-vs-feature-module#:~:text=Feature%20modules%20are%20used%20in,feature%20the%20code%20is%20discarded.)
> Feature modules are used in Instant apps and Android App Bundles so that when app requests a feature while using the instant app or App Bundles, the Play store loads only requested feature module code, and not others. In the case of Instant apps, once the user is done using the feature the code is discarded. If you are working on a regular app and not instant app, I think you should be using Android library module.
Android App Bundles will be used to break up your app into small chunks so that a user doesn't have to download all of the code in your APK if they don't need it.

We use the green one: \/ 
![Screenshot 2020-08-14 at 10 07 14](https://user-images.githubusercontent.com/15942449/90233425-0e5f6100-de16-11ea-85dc-7b263598eaf4.png)

No Dagger or Koin, please use Hilt.

**Comment by tomklecha** [comment]
Ok, thank you

**Comment by Canato** [comment]
Let's compare Hilt x No DI build
